// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1aee7764-85fd-4ba7-ad07-2387b27c6451",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cdUN8tFB0",
    "aws_user_pools_web_client_id": "4q34m58j12ncjscs300p2du57v",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "game",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "sparkadminapp-20181013175940--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://sparkadminapp-20181013175940--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cloud_logic_custom": [
        {
            "name": "sparkapi",
            "endpoint": "https://fo1j7b5lfc.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
